### ISSUE TITLE
Fix elements interchange

### ISSUE THREAD

**Issue by gabrielStanovsky** [vered1986/OKR#26]
Predicates are sometimes wrongly interchanged.

**FEMA Urges East Coast Residents to Prepare for Hurricane Sandy**
FEMA  Urges  East Coast  to  *aim*  for  Hurricane Sandy

The output from PropSWrapper doesn't introduce this error.
@kleinay, can you please check what's your output for this sentence?

```
{'Entities': {'A1': ('Prepare', (6,)),
              'A2': ('Hurricane Sandy', (8, 9)),
              'A3': ('FEMA', (0,)),
              'A4': ('East Coast Residents', (2, 3, 4))},
 'Predicates': {'P1': {'Arguments': ['A1', 'A2', 'A3', 'A4'],
                       'Bare predicate': ('Urges to for', (1, 5, 7)),
                       'Head': {'Lemma': 'Urges',
                                'POS': 'VBZ',
                                'Surface': ('Urges', [1])},
                       'Template': '{A3} Urges {A4} to {A1} for {A2}'}},
 'Sentence': 'FEMA Urges East Coast Residents to Prepare for Hurricane Sandy'}
```

@OriShapira

**Comment by gabrielStanovsky** [comment]
Also seems to happen with entities:

**Hurricane Sandy Bears Down on East Coast**
Hurricane Sandy  Bears  States 
[States is coreferred to "Down"]

**Comment by kleinay** [comment]
Is this error still relevant? I don't know what to check at the json, is it supposed to be a coreference error?

**Comment by kleinay** [comment]
This was fixed. Caused because the lemma of some words was empty (SpaCy couldn't lemmatize it), and therefore was marked as coreferring (same lemma).
