### ISSUE TITLE
Python import stop_words fails

### ISSUE THREAD

**Issue by ypuzikov** [vered1986/OKR#28]
Hi, everyone! 

Thanks for sharing the repository :)

Is it possible that some files are missing or excluded by mistake? 
I am running the baseline as specified in the README file:

`python compute_baseline_subtasks.py ../../data/baseline/dev ../../data/baseline/test`

And I am getting this:

> Traceback (most recent call last):
>   File "compute_baseline_subtasks.py", line 19, in <module>
>     from okr import *
>   File "../common/okr.py", line 11, in <module>
>     from constants import *
>   File "../common/constants.py", line 1, in <module>
>     import stop_words
> ImportError: No module named stop_words

**Comment by ypuzikov** [comment]
The problem is solved by running `pip install stop-words`. 
I guess, it is a good idea to add 'stop-words' as a dependency to the README file.

**Comment by gabrielStanovsky** [comment]
Done.
Thanks!
