### ISSUE TITLE
not taking the head of noun compounds 

### ISSUE THREAD

**Issue by kleinay** [vered1986/OKR#42]
in the single sentence parsing of props_wrapper, I think there is a bug; instead of taking the head of a noun compound as the representative of the (original) long multi-token entity, it takes the first token.

see for example this props_wrapper output:
{'Entities': {'A1': ('Humen', (0,)),
  'A2': ('Rakhine', (6,)),
  'A3': ('Rights', (1,)),
  'A4': ('Watch', (2,)),
  'A5': ('satelite', (3,)),
  'A6': ('images', (4,)),
  'A7': ('destruction', (7,))},
 'Predicates': {'P1': {'Arguments': ['A1', 'A2'],
   'Bare predicate': ('show', (5,)),
   'Head': {'Lemma': 'show', 'POS': 'VBP', 'Surface': ('show', [5])},
   'Template': '{A1} show {A2}'},
  'P2': {'Arguments': ('A1', 'A3'),
   'Bare predicate': ('IMPLICIT', (-1,)),
   'Head': {'Lemma': 'IMPLICIT', 'POS': 'IMPLICIT', 'Surface': 'IMPLICIT'},
   'Template': '{A1} {A3}'},
  'P3': {'Arguments': ('A1', 'A4'),
   'Bare predicate': ('IMPLICIT', (-1,)),
   'Head': {'Lemma': 'IMPLICIT', 'POS': 'IMPLICIT', 'Surface': 'IMPLICIT'},
   'Template': '{A1} {A4}'},
  'P4': {'Arguments': ('A1', 'A5'),
   'Bare predicate': ('IMPLICIT', (-1,)),
   'Head': {'Lemma': 'IMPLICIT', 'POS': 'IMPLICIT', 'Surface': 'IMPLICIT'},
   'Template': '{A1} {A5}'},
  'P5': {'Arguments': ('A1', 'A6'),
   'Bare predicate': ('IMPLICIT', (-1,)),
   'Head': {'Lemma': 'IMPLICIT', 'POS': 'IMPLICIT', 'Surface': 'IMPLICIT'},
   'Template': '{A1} {A6}'},
  'P6': {'Arguments': ('A2', 'A7'),
   'Bare predicate': ('IMPLICIT', (-1,)),
   'Head': {'Lemma': 'IMPLICIT', 'POS': 'IMPLICIT', 'Surface': 'IMPLICIT'},
   'Template': '{A2} {A7}'}},
 'Sentence': 'Humen Rights Watch satellite images show Rakhine destruction'}

the dependency tree states that "images" is the head of "Humen Rights Watch satellite images", but all propositions (P1 and all the implicits) take "Humen" as the argument.

**Comment by kleinay** [comment]
after a dive in the code, I believe this is because the function get_node_ind() is used when creating the element symbol (thus giving the index of the "head" of the entity, saved at tok_ind_to_symbol). this get_node_ind() gives the minimal index of the node, and not the index of the head.
@gabrielStanovsky , would it be risky to change this function to return the head of the node?

**Comment by gabrielStanovsky** [comment]
Sorry for the delay.
I think the fix you made makes sense. I believe that the dependency parser always returns the last word in the compound as the head.
