### ISSUE TITLE
props wrapper- add sentence-id to symbols

### ISSUE THREAD

**Issue by kleinay** [vered1986/OKR#6]
I would like to ask for another feature in the props_wrapper component:
currnelty the parse function is getting only the sentence string - pw.parse(sent).
I would like it to get also a string representing the sentence_id - pw.parse(sent, sent_id).
This sent_id string would be appended to each symbol created by the parsers. i.e. the entities\proposition "keys".  
e.g. if I give sent_id="1", then the Entities keys would be "A1_1", "A1_2" and so on, and same for Propositions. 
This feature would be usefull as it allow me to treat these "symbols"\"keys" as global unique IDs of the entities\propositions.

**Comment by gabrielStanovsky** [comment]
@kleinay, Here's what I have in mind:

"A1_1" would still be a local symbol which you'll have to convert to some global cluster id.
So in any case you'll have to have some mapping saying "A1_1" is in fact "E102", for instance, right?
If so, then let's call it ```local_to_global```.

So the way I see it,  once you'll have this mapping, in any case you'll need to iterate over all sentences, and do something like:

```python
for (sent_id, props_parse) in enumerate([pw.parse(sent) for sent in raw_sents]):
   for pred_name, pred_data in props_parse["Predicates"].iteritems():
      global_template = copy(pred_data["Template"]) # This is where the global template will be built
      for local_arg_name in pred_data["Arguments"]:
          # The way I see it, at this point there are 2 options:
          ## 1.) If I don't change my code (note the "join" operation)
          global_arg_name = local_to_global["_".join(sent_id, local_arg_name)]
          ## 2.) If I do change my code 
          global_arg_name = local_to_global[local_arg_name]

          # Business as usual from here:
          global_template.replace(local_arg_name, global_arg_name)
```

If this is indeed all the change in your code, then I'm not sure if it's worth adding more code in my function.
What do you think?
